// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXZW5OH8uyXdcywk3amkvxCnt1JSVEY5o',
    appId: '1:69565847840:web:60f18b48366b38381d5f45',
    messagingSenderId: '69565847840',
    projectId: 'kenalanku-app-48c7b',
    authDomain: 'kenalanku-app-48c7b.firebaseapp.com',
    storageBucket: 'kenalanku-app-48c7b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLnX8dEa_dJhEI16RDWP233v-WTIwFq1k',
    appId: '1:69565847840:android:fc3c2bc83dfe3bec1d5f45',
    messagingSenderId: '69565847840',
    projectId: 'kenalanku-app-48c7b',
    storageBucket: 'kenalanku-app-48c7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEtHWLT6JcFKch_Qq2ROnWlI5HR762yqs',
    appId: '1:69565847840:ios:adc1ba3214a9d7b31d5f45',
    messagingSenderId: '69565847840',
    projectId: 'kenalanku-app-48c7b',
    storageBucket: 'kenalanku-app-48c7b.firebasestorage.app',
    iosBundleId: 'com.example.kenalanku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEtHWLT6JcFKch_Qq2ROnWlI5HR762yqs',
    appId: '1:69565847840:ios:adc1ba3214a9d7b31d5f45',
    messagingSenderId: '69565847840',
    projectId: 'kenalanku-app-48c7b',
    storageBucket: 'kenalanku-app-48c7b.firebasestorage.app',
    iosBundleId: 'com.example.kenalanku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXZW5OH8uyXdcywk3amkvxCnt1JSVEY5o',
    appId: '1:69565847840:web:8d6d23287367521c1d5f45',
    messagingSenderId: '69565847840',
    projectId: 'kenalanku-app-48c7b',
    authDomain: 'kenalanku-app-48c7b.firebaseapp.com',
    storageBucket: 'kenalanku-app-48c7b.firebasestorage.app',
  );
}
